name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          if [ -n "${{ secrets.VITE_SUPABASE_URL }}" ]; then
            echo "VITE_SUPABASE_URL is set"
          else
            echo "VITE_SUPABASE_URL is NOT set"
          fi
          if [ -n "${{ secrets.VITE_SUPABASE_ANON_KEY }}" ]; then
            echo "VITE_SUPABASE_ANON_KEY is set"
          else
            echo "VITE_SUPABASE_ANON_KEY is NOT set"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
          cat .env
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist