name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ vars.VITE_SUPABASE_ANON_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Debug Environment Variables
        run: |
          if [ -n "$VITE_SUPABASE_URL" ]; then
            echo "VITE_SUPABASE_URL is set"
          else
            echo "VITE_SUPABASE_URL is NOT set"
          fi
          if [ -n "$VITE_SUPABASE_ANON_KEY" ]; then
            echo "VITE_SUPABASE_ANON_KEY is set"
          else
            echo "VITE_SUPABASE_ANON_KEY is NOT set"
          fi

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist