name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Create env file
        run: |
          touch .env
          echo VITE_SUPABASE_URL="https://qkicbsscsauxgwdktojb.supabase.co" >> .env
          echo VITE_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFraWNic3Njc2F1eGd3ZGt0b2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5OTUxMzcsImV4cCI6MjA1NjU3MTEzN30.02D1hUP6nVjNV-qjJPyIZp2YJJ27yFBHX1r7i6bjSZ4" >> .env

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist